[package]
name = 'fieldopt'
publish = false
version = '0.1.0'
edition = '2021'
rust-version = '1.70'

[lib]
crate-type = [ 'rlib', 'staticlib' ]
name = 'fieldopt'

[[bin]]
name = 'document'
path = 'document.rs'

[dependencies]
extendr-api = '0.9'
fieldopt-core = { git = 'https://github.com/castlaboratory/fieldopt-core', rev = '40137daabf069c9c4795d77e61e7b1a9f2aa3f98' }

[profile.release]
lto = true
codegen-units = 1
