test_that("haversine and euclidean matrices are symmetric with zero diagonal", {
  pts <- data.frame(unit = c("depot", "a", "b"), lat = c(-8.05, -8.10, -8.00), lon = c(-34.90, -34.95, -34.85))
  m <- travel_matrix(pts)
  expect_s3_class(m, "fieldopt_matrix")
  expect_equal(dim(m), c(3, 3))
  expect_equal(diag(m), c(depot = 0, a = 0, b = 0))
  expect_equal(unclass(m)[1, 2], unclass(m)[2, 1])
  # Recife to a point 0.05 degrees south is about 5.6 km
  expect_equal(unclass(m)["depot", "a"], 7.82, tolerance = 0.01)
  e <- travel_matrix(data.frame(x = c(0, 3), y = c(0, 4)), method = "euclidean")
  expect_equal(unclass(e)[1, 2], 5)
  expect_equal(rownames(e), c("u1", "u2"))
  expect_equal(attr(e, "unit"), "distance")
})

test_that("supplied matrices are wrapped and validated", {
  pts <- data.frame(unit = c("d", "a"), x = c(0, 1), y = c(0, 0))
  net <- matrix(c(0, 12, 12, 0), 2)
  m <- travel_matrix(pts, method = "euclidean", matrix = net, unit = "min")
  expect_equal(unclass(m)[1, 2], 12)
  expect_equal(attr(m, "method"), "supplied")
  expect_equal(attr(m, "unit"), "min")
  expect_error(travel_matrix(pts, method = "euclidean", matrix = matrix(0, 3, 3)), "2 x 2")
  expect_error(travel_matrix(pts, method = "euclidean", matrix = -net), "non-negative")
  expect_error(travel_matrix(data.frame(unit = c("a", "a"), x = 1:2, y = 1:2), method = "euclidean"), "distinct")
  expect_error(travel_matrix(data.frame(x = 1, y = 1)), "lat")
  expect_message(print(m), "Travel matrix")
})

test_that("the cost model prices travel, units and interviews", {
  cm <- field_cost_model(per_travel = 2, per_unit = 30, per_interview = 10, interviews_per_unit = 4, currency = "BRL")
  expect_s3_class(cm, "field_cost_model")
  cost <- fieldopt:::cost_of(cm, travel_total = 100, units_visited = 5, unit_index = 1:5)
  expect_equal(unname(cost[c("travel", "units", "interviews", "total")]), c(200, 150, 200, 550))
  f <- field_cost_model(1, 0, 10, interviews_per_unit = function(i) i)
  expect_equal(unname(fieldopt:::cost_of(f, 0, 3, c(2, 5, 9))[["interviews"]]), 160)
  expect_error(field_cost_model(per_travel = -1), "non-negative")
  expect_message(print(cm), "BRL")
})
