# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib fieldopt, .registration = TRUE
NULL

#' Travel matrix from coordinates: `method` is "haversine" (lat, lon in
#' degrees, kilometres) or "euclidean". Returns the row-major n x n vector.
#' @noRd
travel_matrix_rs <- function(a, b, method) .Call(wrap__travel_matrix_rs, a, b, method)

#' GRASP routing. `matrix` is the row-major n x n travel matrix; `depot` and
#' `units` are 0-based indices.
#' @noRd
route_rs <- function(matrix, n, depot, units, max_length, max_stops, iterations, alpha, seed) .Call(wrap__route_rs, matrix, n, depot, units, max_length, max_stops, iterations, alpha, seed)

#' Size-proportional inclusion probabilities summing to `n`.
#' @noRd
inclusion_probabilities_rs <- function(size, n) .Call(wrap__inclusion_probabilities_rs, size, n)

#' Local pivotal method 2 on an n x d row-major coordinate matrix.
#' @noRd
local_pivotal_rs <- function(coords, d, pi, seed) .Call(wrap__local_pivotal_rs, coords, d, pi, seed)

#' Horvitz-Thompson total.
#' @noRd
ht_total_rs <- function(y, pi, sampled) .Call(wrap__ht_total_rs, y, pi, sampled)

#' Local-mean variance estimator of the Horvitz-Thompson total.
#' @noRd
local_mean_variance_rs <- function(coords, d, y, pi, sampled) .Call(wrap__local_mean_variance_rs, coords, d, y, pi, sampled)

#' Simple-random-sampling variance of the total.
#' @noRd
srs_variance_rs <- function(y, sampled, big_n) .Call(wrap__srs_variance_rs, y, sampled, big_n)

#' Cost-aware allocation: `mode` is "variance" (target variance) or "budget".
#' @noRd
allocate_rs <- function(size, sd, cost, target, mode) .Call(wrap__allocate_rs, size, sd, cost, target, mode)

#' Version of the engine crate.
#' @noRd
core_version_rs <- function() .Call(wrap__core_version_rs)

# nolint end
